server {
    listen 80;
    intentionally_broken_for_rollback_test;

    # 정적 파일 (index.html 등)
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }

    # User Service 프록시
    location /api/users/ {
        proxy_pass http://user-service:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Order Service 프록시
    location /api/orders/ {
        proxy_pass http://order-service:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
